## Feature Engineering

In [12]:
import pandas as pd


df = pd.read_csv('../datasets/processed/processed.csv')
df.head()

,season,holiday,workingday,weathersit,temp,hum,windspeed,cnt,dayofweek,month,year
0,1,0,0,2,0.344167,0.805833,0.160446,985,5,1,2011
1,1,0,0,2,0.363478,0.696087,0.248539,801,6,1,2011
2,1,0,1,1,0.196364,0.437273,0.248309,1349,0,1,2011
3,1,0,1,1,0.200000,0.590435,0.160296,1562,1,1,2011
4,1,0,1,1,0.226957,0.436957,0.186900,1600,2,1,2011

In [13]:
df.columns

Index(['season', 'holiday', 'workingday', 'weathersit', 'temp', 'hum',
       'windspeed', 'cnt', 'dayofweek', 'month', 'year'],
      dtype='str')

In [14]:
## cyclic encoding on month and day of week

import numpy as np

df["month_sin"] = np.sin(2 * np.pi * df["month"] / 12)
df["month_cos"] = np.cos(2 * np.pi * df["month"] / 12)

df["dayofweek_sin"] = np.sin(2 * np.pi * df["dayofweek"] / 7)
df["dayofweek_cos"] = np.cos(2 * np.pi * df["dayofweek"] / 7)

df.drop(columns=["month", "dayofweek"], inplace=True)
df.head()

,season,holiday,workingday,weathersit,temp,hum,windspeed,cnt,year,month_sin,month_cos,dayofweek_sin,dayofweek_cos
0,1,0,0,2,0.344167,0.805833,0.160446,985,2011,0.5,0.866025,-0.974928,-0.222521
1,1,0,0,2,0.363478,0.696087,0.248539,801,2011,0.5,0.866025,-0.781831,0.623490
2,1,0,1,1,0.196364,0.437273,0.248309,1349,2011,0.5,0.866025,0.000000,1.000000
3,1,0,1,1,0.200000,0.590435,0.160296,1562,2011,0.5,0.866025,0.781831,0.623490
4,1,0,1,1,0.226957,0.436957,0.186900,1600,2011,0.5,0.866025,0.974928,-0.222521

In [15]:
final_data = df.copy()

final_data.to_csv('../datasets/final/final.csv', index=False)